In [68]:
# LSTM with Dropout
import numpy
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
from keras import regularizers
from keras.layers.core import SpatialDropout1D
from keras.layers.convolutional import Conv1D
from keras.layers.pooling import MaxPooling1D
from keras.models import model_from_json
from keras.callbacks import TensorBoard
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np
import nltk
import os


json_file = open('model.json','r')
loaded_model_json = json_file.read()
json_file.close()
model = model_from_json(loaded_model_json)
# model = model_from_json("model.json")
model.load_weights("model.h5")
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [69]:
def predict(PARAMS):
    top_words = 500
    tokenizer = Tokenizer(num_words=top_words)
    tokenizer.fit_on_texts(reviews)
    sequences = tokenizer.texts_to_sequences(reviews)
    data = pad_sequences(sequences, maxlen=top_words)
    res = model.predict_proba(data,  verbose=0)
    print(res)
    return res

def walk_file(file_name, score, review, review_score):
    file_json = []
    with open(file_name, 'rb') as f:
#             line = f.readline()
            lines = [l.decode('utf8', 'ignore') for l in f.readlines()]
            json_data = json.loads(line)
            data = []
            for d in json_data:
                data.append(d['review'])
            file_json = (predict(data)).tolist()
            f.close()
            file_name = os.path.splitext(file_name)[0]
            print(file_name+str(" done! \n"))
            filename = file_name+str('_res.json')
            print(type(file_json))
            save2json(file_json, filename)
            return score, review, review_score

def save2json(dictObj, filename):
    jsonObj = json.dumps(dictObj)
    fileObject = open(filename,'w')
    fileObject.write(jsonObj)
    fileObject.close()  

In [70]:
g = os.walk("./raw_data/")
for path, d, filelist in g:
    print(d)
    for filename in filelist:
        file_name = os.path.join(path, filename)
        score = []
        review = []
        review_score = []
        walk_file(file_name, score, review, review_score)
#         scores.append(score)
#         reviews.append(review)
#         review_scores.append(review_score)

['res']
[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.11164165]
 [0.892241  ]
 [0.8358741 ]
 [0.9628246 ]
 [0.3655423 ]
 [0.8704487 ]
 [0.7350739 ]
 [0.68355346]
 [0.9610788 ]
 [0.8863245 ]
 [0.25516903]
 [0.9668452 ]
 [0.9029503 ]
 [0.7778714 ]
 [0.03450894]
 [0.88930565]
 [0.8578912 ]
 [0.42231774]
 [0.50355226]
 [0.9392918 ]
 [0.9331963 ]
 [0.5330865 ]
 [0.53067905]
 [0.9337201 ]
 [0.95326424]
 [0.81217146]
 [0.5818854 ]]
./raw_data/Baywatch done! 

<class 'list'>
[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.11164165]
 [0.892241  ]
 [0.8358741 ]
 [0.9628246 ]
 [0.3655423 ]
 [0.8704487 ]
 [0.7350739 ]
 [0.68355346]
 [0.9610788 ]
 [0.8863245 ]
 [0.25516903]
 [0.9668452 ]
 [0.9029503 ]
 [0.7778714 ]
 [0.03450894]
 [0.88930565]
 [0.8578912 ]
 [0.42231774]
 [0.50355226]
 [0.9392918 ]
 [0.9331963 ]
 [0.5330865 ]
 [0.53067905]
 [0.9337201 ]
 [0.95326424]
 [0.81217146]
 [0.5818854 ]]
./raw_data/Alien: Covenant done! 

<class 'list'>
[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.11164165]
 

[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.11164165]
 [0.892241  ]
 [0.8358741 ]
 [0.9628246 ]
 [0.3655423 ]
 [0.8704487 ]
 [0.7350739 ]
 [0.68355346]
 [0.9610788 ]
 [0.8863245 ]
 [0.25516903]
 [0.9668452 ]
 [0.9029503 ]
 [0.7778714 ]
 [0.03450894]
 [0.88930565]
 [0.8578912 ]
 [0.42231774]
 [0.50355226]
 [0.9392918 ]
 [0.9331963 ]
 [0.5330865 ]
 [0.53067905]
 [0.9337201 ]
 [0.95326424]
 [0.81217146]
 [0.5818854 ]]
./raw_data/Atomic Blonde done! 

<class 'list'>
[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.11164165]
 [0.892241  ]
 [0.8358741 ]
 [0.9628246 ]
 [0.3655423 ]
 [0.8704487 ]
 [0.7350739 ]
 [0.68355346]
 [0.9610788 ]
 [0.8863245 ]
 [0.25516903]
 [0.9668452 ]
 [0.9029503 ]
 [0.7778714 ]
 [0.03450894]
 [0.88930565]
 [0.8578912 ]
 [0.42231774]
 [0.50355226]
 [0.9392918 ]
 [0.9331963 ]
 [0.5330865 ]
 [0.53067905]
 [0.9337201 ]
 [0.95326424]
 [0.81217146]
 [0.5818854 ]]
./raw_data/Thor: Ragnarok done! 

<class 'list'>
[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.11164165]
 [0.8

[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.11164165]
 [0.892241  ]
 [0.8358741 ]
 [0.9628246 ]
 [0.3655423 ]
 [0.8704487 ]
 [0.7350739 ]
 [0.68355346]
 [0.9610788 ]
 [0.8863245 ]
 [0.25516903]
 [0.9668452 ]
 [0.9029503 ]
 [0.7778714 ]
 [0.03450894]
 [0.88930565]
 [0.8578912 ]
 [0.42231774]
 [0.50355226]
 [0.9392918 ]
 [0.9331963 ]
 [0.5330865 ]
 [0.53067905]
 [0.9337201 ]
 [0.95326424]
 [0.81217146]
 [0.5818854 ]]
./raw_data/res/Alien: Covenant_res_res done! 

<class 'list'>
[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.11164165]
 [0.892241  ]
 [0.8358741 ]
 [0.9628246 ]
 [0.3655423 ]
 [0.8704487 ]
 [0.7350739 ]
 [0.68355346]
 [0.9610788 ]
 [0.8863245 ]
 [0.25516903]
 [0.9668452 ]
 [0.9029503 ]
 [0.7778714 ]
 [0.03450894]
 [0.88930565]
 [0.8578912 ]
 [0.42231774]
 [0.50355226]
 [0.9392918 ]
 [0.9331963 ]
 [0.5330865 ]
 [0.53067905]
 [0.9337201 ]
 [0.95326424]
 [0.81217146]
 [0.5818854 ]]
./raw_data/res/It_res done! 

<class 'list'>
[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.11164

[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.11164165]
 [0.892241  ]
 [0.8358741 ]
 [0.9628246 ]
 [0.3655423 ]
 [0.8704487 ]
 [0.7350739 ]
 [0.68355346]
 [0.9610788 ]
 [0.8863245 ]
 [0.25516903]
 [0.9668452 ]
 [0.9029503 ]
 [0.7778714 ]
 [0.03450894]
 [0.88930565]
 [0.8578912 ]
 [0.42231774]
 [0.50355226]
 [0.9392918 ]
 [0.9331963 ]
 [0.5330865 ]
 [0.53067905]
 [0.9337201 ]
 [0.95326424]
 [0.81217146]
 [0.5818854 ]]
./raw_data/res/Logan_res done! 

<class 'list'>
[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.11164165]
 [0.892241  ]
 [0.8358741 ]
 [0.9628246 ]
 [0.3655423 ]
 [0.8704487 ]
 [0.7350739 ]
 [0.68355346]
 [0.9610788 ]
 [0.8863245 ]
 [0.25516903]
 [0.9668452 ]
 [0.9029503 ]
 [0.7778714 ]
 [0.03450894]
 [0.88930565]
 [0.8578912 ]
 [0.42231774]
 [0.50355226]
 [0.9392918 ]
 [0.9331963 ]
 [0.5330865 ]
 [0.53067905]
 [0.9337201 ]
 [0.95326424]
 [0.81217146]
 [0.5818854 ]]
./raw_data/res/Phantom Thread_res done! 

<class 'list'>
[[0.05427453]
 [0.7778896 ]
 [0.8862109 ]
 [0.1116416